# Generated by Django 4.0.5 on 2022-06-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delever_finish',
            new_name='deliver_finish',
        ),
    ]
